# Generated by Django 3.2.7 on 2021-09-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=1)),
                ('cedula', models.CharField(max_length=9)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telfPrincipal', models.CharField(max_length=15)),
                ('telfSecundario', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
