# Generated by Django 3.2.4 on 2021-11-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='estado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
