# Generated by Django 3.2.7 on 2021-09-30 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('poblacionObjetivo', models.CharField(max_length=50)),
                ('antecedentes', models.CharField(blank=True, max_length=280, null=True)),
                ('objetivoNegocio', models.CharField(max_length=280)),
                ('objetivoOrganizacion', models.CharField(max_length=280)),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='correoUcab',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='participante',
            name='cedula',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='genero',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='ParticipanteCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.carrera')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.participante')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.sede')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='carreras',
            field=models.ManyToManyField(through='backend.ParticipanteCarrera', to='backend.Carrera'),
        ),
        migrations.AddField(
            model_name='participante',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.colegio'),
        ),
    ]
