# Generated by Django 3.2.6 on 2021-08-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='noCedula',
        ),
    ]
