# Generated by Django 3.2.7 on 2021-10-06 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='MuestraPonderada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=280)),
                ('poblacion', models.IntegerField()),
                ('muestra', models.IntegerField()),
                ('edicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.edicion')),
            ],
        ),
    ]
