# Generated by Django 3.2.4 on 2021-09-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_participante_carreras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='carreras',
        ),
        migrations.CreateModel(
            name='ParticipanteCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('esEgresado', models.BooleanField(blank=True, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.carrera')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.participante')),
            ],
        ),
    ]
