# Generated by Django 3.2.4 on 2021-10-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211004_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.colegio'),
        ),
    ]
