# Generated by Django 3.2.4 on 2021-09-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_participante_nocedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
