# Generated by Django 3.2.4 on 2022-01-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='prueba',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
