# Generated by Django 3.2.7 on 2021-11-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_muestraponderada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muestraponderada',
            old_name='condicion',
            new_name='primeraCondicion',
        ),
        migrations.AddField(
            model_name='muestraponderada',
            name='segundaCondicion',
            field=models.CharField(default=1, max_length=280),
            preserve_default=False,
        ),
    ]
