# Generated by Django 3.2.4 on 2021-10-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_participante_colegio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='correoUcab',
            field=models.CharField(blank=True, default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
