# Generated by Django 3.2.7 on 2021-09-30 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_edicion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edicion',
            old_name='TotalMuestra',
            new_name='totalMuestra',
        ),
        migrations.AddField(
            model_name='edicion',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.estudio'),
        ),
    ]
