# Generated by Django 3.2.7 on 2022-01-13 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211105_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=280, null=True)),
                ('fechaCreacion', models.DateField()),
                ('fechaUltimaModificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=280)),
                ('fechaCreacion', models.DateField()),
                ('fechaUltimaModificacion', models.DateField()),
                ('listaCodigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.listacodigo')),
            ],
        ),
    ]
