# Generated by Django 3.2.4 on 2021-09-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_participante_carreras'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantecarrera',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.sede'),
            preserve_default=False,
        ),
    ]
