# Generated by Django 3.2.7 on 2021-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210930_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicion',
            name='periodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
