# Generated by Django 3.2.4 on 2021-10-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_participante_correoucab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='correoUcab',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
