# Generated by Django 3.2.7 on 2022-01-12 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211105_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionCualitativa', models.CharField(blank=True, max_length=280, null=True)),
                ('modalidadCualitativa', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcionCuantitativa', models.CharField(blank=True, max_length=280, null=True)),
                ('modalidadCuantitativa', models.CharField(blank=True, max_length=50, null=True)),
                ('edicionId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.edicion')),
            ],
        ),
    ]
