# Generated by Django 3.2.7 on 2022-01-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_categoria_listacodigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listacodigo',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listacodigo',
            name='fechaUltimaModificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
