# Generated by Django 3.2.4 on 2022-01-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220111_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.lugar'),
        ),
    ]
