# Generated by Django 3.2.4 on 2021-09-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210916_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantecarrera',
            name='esEgresado',
        ),
        migrations.AlterField(
            model_name='participantecarrera',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.sede'),
        ),
    ]
