# Generated by Django 3.2.7 on 2022-01-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20220112_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fechaUltimaModificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
