# Generated by Django 3.2.4 on 2022-01-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_participante_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='municipio',
        ),
    ]
