# Generated by Django 3.2.4 on 2022-01-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220111_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
