# Generated by Django 3.2.7 on 2022-01-14 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220112_2256'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('codigo', 'listaCodigo')},
        ),
    ]
