# Generated by Django 3.2.4 on 2021-09-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_sede_apodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='apodo',
        ),
    ]
