# Generated by Django 3.2.4 on 2021-09-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_sede_apodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='correoUcab',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
