# Generated by Django 3.2.4 on 2021-09-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_participante_correoucab'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='lugar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='cedula',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='correoUcab',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='telfPrincipal',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
