# Generated by Django 3.2.4 on 2021-09-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210922_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='lugar',
        ),
    ]
