from .modelCarrera import *
from .modelSede import *
from .modelColegio import *
from .modelParticipante import *
from .modelParticipanteCarrera import *
from .modelEstudio import *
from .modelEdicion import *
from .modelMuestraPonderada import *
from .modelMetodologia import *