from .participanteCarrera import *
from .participante import *
from backend.models import *
from .muestraPonderada import *
from .estudios import *
from .edicion import *
from .listaCodigo import *
from .lugar import *
from .pregunta import *
from .usuario import *
